# Dependencies
markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sean Montana
tagline:          '3 Things'
description:      'Every day'
url:              http://seanmontana.com
baseurl:          /

author:
  name:           'Sean Montana'
  url:            https://twitter.com/SeanMontanaR

paginate:         5

github:
  repo:           https://github.com/sromocki

gems: [jekyll-paginate, jekyll-gist]
