# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sean Montana
tagline:          '3 Things'
description:      'Every day'
url:              http://seanmontana.com
baseurl:          /

author:
  name:           'Sean Montana'
  url:            https://twitter.com/SeanMontanaR

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sromocki
